
INSERT INTO usuario (id_usuario, nombre, apellidos, email, passwd, telefono, direccion, ciudad, jotas) VALUES
	(NULL, "Juan", "Martinez Sanchez", "juanmartinezsanches@gmail.com", "1234", "684279952", "Paseo Santa Maria de la cabeza nºX", "Madrid", 999 ),
	(NULL, "Jesús", "López Centeno", "jesuslopezcenteno@gmail.com", "1234", "689480915", "c/Fatima nº8 3ºB", "Fuenlabrada", 999 );

INSERT INTO categoria (id_categoria, nombre) VALUES
	(NULL, "Libros, peliculas, musica"),
	(NULL, "Programas informaticos, software y videojuegos"),
	(NULL, "Hardware"),
	(NULL, "Ropa y accesorios"),
	(NULL, "Instrumentos musicales"),
	(NULL, "Articulos Salesianos Atocha");

INSERT INTO producto ( id_producto, titulo_prod, nombre_prod, descripcion, precio, marca_autor, img_1, img_2, id_categoria) VALUES
	( NULL, 
	"Bullet Train Ed. Digital", 
	"Bullet Train", 
	"Brad Pitt interpreta al personaje de Mariquita en Bullet Train, un asesino con mala suerte que está decidido a cumplir su misión pacíficamente tras demasiados 'trabajos' que han descarrilado. Sin embargo, el destino tiene otros planes al situar a Mariquita en una vía de colisión con todo tipo de adversarios letales - conectados y enfrentados entre sí - en el tren más rápido del mundo. Dirigida por David Leitch (Deadpool 2), el final del trayecto es solo el comienzo de este salvaje y trepidante viaje a través del Japón más moderno.", 
	15, 
	"Sony Pictures", 
	"bullettrain1.png", 
	"bullettrain2.png", 
	1),

	( NULL, 
	"El hombre del norte Ed. Digital", 
	"El hombre del norte", 
	"El aclamado director Robert Eggers regresa con 'El hombre del norte', un thriller épico que narra la venganza de un príncipe vikingo tras el asesinato de su padre. La película está protagonizada por los ganadores del Globo de Oro Alexander Skarsgård y Anya Taylor-Joy junto con la ganadora del Oscar Nicole Kidman y los nominados al Oscar Ethan Hawke y Willem Dafoe y la cantante Björk.", 
	15, 
	"Universal Pictures", 
	"hombrenorte1.png", 
	"hombrenorte2.png", 
	1),

	( NULL, 
	"Top Gun: Maverick Ed. Digital", 
	"Top Gun: Maverick", 
	"Pete 'Maverick' Mitchell (Tom Cruise), tras más de treinta años de servicio como aviador naval de alto nivel, está donde debe estar como un experto piloto de pruebas. Sin embargo, Maverick, debe enfrentarse a los fantasmas de su pasado cuando vuelve al TOP GUN para entrenar a un grupo de graduados de élite y se encuentra cara a cara con el teniente Bradshaw (Miles Teller), el hijo de su antiguo compañero de vuelo, 'Goose'. Las amargas rivalidades se encienden mientras los pilotos se preparan para una misión real muy peligrosa que requerirá el máximo sacrificio a los pocos elegidos para llevarla a cabo.", 
	15, 
	"Paramount Pictures", 
	"topgun1.png", 
	"topgun2.png", 
	1),

	( NULL, 
	"Wrath of man Ed. Digital", 
	"Wrath of man", 
	"Jason Statham teams with director Guy Ritchie for the fourth time in this explosive remake of the French actioner 'Cash Truck'. Statham stars as H, an armored truck company employee who finds himself up to his neck in danger when his mysterious and violent past collides with the present, thrusting him smack in the middle of a daring heist-and maybe affording him the opportunity to settle a very personal score. With Holt McCallany, Scott Eastwood, Josh Hartnett, and Andy Garcia. 119 min. Widescreen; Soundtrack: English.", 
	15, 
	"Warner Pictures", 
	"wrathofman1.png", 
	"wrathofman2.png", 
	1),

	( NULL, 
	"LA LA Land Ed. Digital", 
	"LA LA Land", 
	"La La Land. La película está escrita y dirigida por Damien Chazelle, ganador del Oscar a la Mejor Dirección, y protagonizada por el nominado al Oscar al Mejor Actor Ryan Gosling, y la ganadora del Oscar a la Mejor Actriz Emma Stone. Ambos dan vida a Mia, una actriz en los inicios de su carrera, y Sebastian, un músico de jazz, que tratan de hacerse un hueco en una ciudad capaz de destrozar esperanzas y romper corazones. Ambientada en el Los Ángeles de hoy en día, este original musical describe la sencillez de la vida y las alegrías y decepciones que dos jóvenes se encuentran en el camino a sus sueños. La mágica visión de Damien Chazelle sobre el Los Ángeles contemporáneo está, sin duda, destinada a convertirse en un clásico y en el icono de una época.", 
	15, 
	"Sony Pictures", 
	"lalaland.png", 
	"lalaland2.png", 
	1),

	( NULL, 
	"Morbius Ed. Digital", 
	"Morbius", 
	"Llega uno de los personajes más cautivadores y conflictivos del Universo Marvel de Sony Pictures, el ganador del Oscar Jared Leto (2013, Mejor Actor de Reparto, Dallas Buyers Club) se transforma en el enigmático antihéroe Michael Morbius. El doctor Morbius tiene una extraña enfermedad sanguínea y, resuelto a salvar a otros que corren su misma suerte, decide arriesgar el todo por el todo. De primeras parece un éxito clamoroso, pero hay algo oscuro que se desata dentro de él. ¿Podrá su parte buena anteponerse a la mala? ¿O sucumbirá ante sus inquietantes nuevos impulsos?", 
	15, 
	"Sony Pictures", 
	"morbus1.png", 
	"morbus2.png", 
	1),

	( NULL, 
	"InterStellar Ed. Digital", 
	"InterStellar", 
	"Interstellar (conocida como Interestelar en Hispanoamérica) es una película épica de drama y ciencia ficción británico-estadounidense y canadiense de 2014, dirigida por Christopher Nolan y protagonizada por Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine y Matt Damon. Ambientada en un futuro distópico donde la humanidad está luchando por sobrevivir, cuenta la historia de un grupo de astronautas que viajan a través de un agujero de gusano cerca de Saturno en busca de un nuevo hogar para la humanidad.", 
	15, 
	"Warner Pictures", 
	"inter1.png", 
	"inter2.png", 
	1),

	( NULL, 
	"Salvar al soldado Ryan Ed. Digital", 
	"Salvar al soldado Ryan", 
	"Segunda Guerra Mundial (1939-1945). Tras el desembarco de los Aliados en Normandía, a un grupo de soldados americanos se le encomienda una peligrosa misión: poner a salvo al soldado James Ryan. Los hombres de la patrulla del capitán John Miller deben arriesgar sus vidas para encontrar a este soldado, cuyos tres hermanos han muerto en la guerra. Lo único que se sabe del soldado Ryan es que se lanzó con su escuadrón de paracaidistas detrás de las líneas enemigas.", 
	15, 
	"Paramount Pictures", 
	"salvsold1.png", 
	"salvsold2.png", 
	1),

	( NULL, 
	"Gladiator Ed. Digital", 
	"Gladiator ", 
	"Winner of Best Picture and Best Actor Academy Awards, director Ridley Scott's stirring spectacle stars Russell Crowe as heroic Roman general Maximus. Chosen to succeed ailing emperor Marcus Aurelius (Richard Harris), Maximus is marked for death by the scheming imperial son (Joaquin Phoenix). After being sold into slavery, Maximus emerges as the empire's greatest gladiator and seeks vengeance in a showdown at the Colosseum. With Oliver Reed, Connie Nielsen, Djimon Hounsou. 155 min. Widescreen; Soundtrack: English. Three-disc set.", 
	15, 
	"Paramount Pictures", 
	"gladiator1.png", 
	"gladiator2.png", 
	1),
	
	
	( NULL, 
	"Scarface Ed. Digital", 
	"Scarface", 
	"En 1980, el fin del bloqueo de Puerto Muriel a Fidel Castro produce un éxodo masivo de cubanos a Estados Unidos. Uno de ellos es Tony Montana (Al Pacino) que, cansado de la miseria, busca alcanzar el gran 'sueño americano'. Sin embargo, todos los comienzos son duros y tras terminar en la cárcel y conseguir escapar, el único trabajo que encuentra es en un puesto de comida ambulante junto a su amigo Manny. Cansados de no alcanzar la vida con la que soñaban y decididos a ganar dinero de verdad, Tony y Manny comienzan a hacerse un nombre en la ciudad a base de trabajos sucios, logrando así levantar su propio imperio. Sin embargo, descubrirán que todo poder tiene un alto precio a pagar.", 
	15, 
	"Universal Pictures", 
	"scarface1.png", 
	"scarface2.png", 
	1),

	(NULL, 
	'Nirvana - Nevermind Ed. Digital','Nevermind',
	"Nevermind (en español: 'No importa') es el segundo álbum de estudio de la banda estadounidense de grunge Nirvana, publicado en septiembre de 1991. Producido por Butch Vig, Nevermind fue el primer lanzamiento de la banda con DGC Records. El líder de la agrupación, Kurt Cobain, trató de hacer música fuera de los límites restrictivos de la escena grunge de Seattle, aprovechando la influencia de grupos como los Pixies y su uso de la dinámica de canciones ruidosas y calmadas, con grandes composiciones y sonidos.'",
	13.99,
	'Nirvana',
	'nevermind1.png',
	NULL,
	1),

	(NULL,
	'Michael Jackson - Thriller, Ed. Digital',
	'Thriller',
	'Thriller es el sexto álbum de estudio del artista estadounidense Michael Jackson, publicado el 30 de noviembre de 1982 por Epic Records. Producido por Quincy Jones —quien trabajó también en el álbum Off the Wall (1979) del mismo artista—, la obra está compuesta por un balance de varios géneros musicales: entre disco y rock, funk y balada, R&B y pop.3​ El propio Jackson escribió cuatro de las nueve canciones del álbum',
	18.95,
	'Michael Jackson',
	'thriller.png',
	NULL,
	1),

	(NULL,
	'Hoke - BBO Ed. Digital',
	'BBO ',
	'Álbum musical de Hoke y Louis Amoeba',
	13.48,
	'Hoke',
	'bbo.png',
	NULL,
	1),

	(NULL,
	'Hakuna - Descalzos Ed. Digital',
	'Descalzos',
	'Álbum musical de Hakuna group music. Sacado en 2022. Para remover los corazones.',
	19.99,
	'Hakuna Group Music',
	'descalzos.png',
	NULL,
	1),

	(NULL,
	'Dover - Late at night Ed. Digital',
	'Late at night',
	'Late At Night es el tercer álbum de estudio de la banda de rock española Dover. Fue publicado el 28 de junio de 1999 bajo las compañías Loli Jackson Records y Chrysalis Records.',
	9.98,
	'Dover',
	'dover.png',
	NULL,
	1),

	(NULL,
	'Taize - Christe Lux Mundi Ed. Digital',
	'Christe Lux Mundi',
	'La Comunidad de Taizé es una comunidad monástica cristiana ecuménica, fundada en 1940 por el teólogo suizo Roger Schutz, conocido como Hermano Roger, en la localidad de Taizé, Francia, que continúa siendo su sede. Es reconocida mundialmente como un foco de ecumenismo.',
	23,
	'Taizé',
	'luxmundi.png',
	NULL,
	1),

	(NULL,
	'Iron Maiden - Fear of Dark Ed. Digital',
	'Fear of Dark',
	'Iron Maiden continúa reeditando su discografía remasterizada en formato CD digipack. The studio Collection - remastered se publica en formato CD digital, con el mismo Tracklisting que las versiones originales. Las grabaciones se han tomado de los mismos remastered que los lanzamientos digitales de alta resolución de 2015. Los álbumes se están lanzando cronológicamente en lotes de cuatro.',
	18.5,
	'Iron Maiden',
	'fearofdark.png',
	NULL,
	1),

	(NULL,
	'Wisin & Yandel - De otra manera Ed. Digital',
	'De otra manera',
	'De otra manera es el tercer álbum de estudio del dúo de reguetón puertorriqueño Wisin & Yandel publicado en 2002.​ Contó con la colaboración de los artistas Alexis & Fido, Divino y Baby Ranks',
	9.99,
	'Wisin & Yandel',
	'deotramanera.png',
	NULL,
	1),

	(NULL,
	'Despistaos - Lo que hemos vivido Ed. Digital',
	'Lo que hemos vivido',
	'Con cuatro discos en el mercado, Despistaos lanza su primer recopilatorio. Seguramente, no nos engañemos, porque el sello quería recoger un poco del éxito logrado por poner sintonía a la popular serie de televisión “Física o Química”.',
	13.69,
	'Despistaos',
	'loquehemosvivido.png',
	NULL,
	1),

	(NULL,
	'Taylor Swift - Midnights Ed. Digital',
	'Taylor Swift - Midnights',
	'Taylor Swift pública el próximo 21 de octubre nuevo álbum de estudio que lleva por título “Midnights”. Es una colección de canciones escritas en mitad de la noche: Un viaje a través de los terrores y de los dulces sueños. Los suelos por los que deambulamos y los demonios a los que nos enfrentamos – las historias de 13 noches sin dormir desperdigadas a lo largo de la vida de Taylor',
	23,
	'Taylor Swift',
	'midnights.png',
	NULL,
	1),

	(NULL, 
	'Adobe Premiere',
	'Adobe Premiere',
	'Software de edición de vídeo fácil
	Opciones de edición automática y de IA para conseguir vídeos increíbles
	27 cambios guiados paso a paso para guiarte en el proceso
	Creaciones personalizadas, como presentaciones de diapositivas y collages de vídeo
	Compra única, sin necesidad de suscripción',
	32.50,
	'Adobe',
	'premiere.png',
	NULL,
	2),

	(NULL, 
	'Adobe Photoshop',
	'Adobe Photoshop',
	'Crea y mejora fotos e ilustraciones con herramientas mejoradas y tutoriales. Impresión en 3D. Actualizaciones gratuitas. Integración de Adobe XD. Behance ProSite. Búsqueda en aplicaciones. Tutoriales paso a paso. Reducción temblor cámara. Plantillas de Adobe Stock.',
	32.50,
	'Adobe',
	'photoshop.png',
	NULL,
	2),

	(NULL,
	'Win RAR','Win RAR',
	'WinRAR es un software de compresión de datos desarrollado por Yevgueni Roshal y distribuido por Ron Dwight. Fue lanzado el 22 de abril de 1995.​ Aunque es un producto comercial, existe una versión de prueba gratuita de 40 días, al terminar este periodo se mostrará un aviso para comprar una licencia al abrir WinRAR.',
	32.50,
	'Win Rar',
	'winrar.png',
	NULL,
	2),

	(NULL, 
	'Microsoft Office 365',
	'Microsoft Office 365',
	'Compra y descarga planes para tu familia o negocio para apps de Office en tus dispositivos. Colabora mejor. Apps Microsoft 365®. Apps Microsoft® novedosas. Seguridad de categoría. Crea, edita y presenta. Colabora en tiempo real. 1 TB almacenamiento nube.',
	32.50,
	'Microsoft',
	'365.png',
	NULL,
	2),

	(NULL, 
	'Microsoft Visio',
	'Microsoft Visio',
	'Con Visio en su PC o dispositivo móvil, puede: Organizar visualmente ideas complejas. Usar cientos de plantillas, incluidos gráficos de flujo, escalas de tiempo, planos de planta y muchas más. Agregar y conectar imágenes, texto y formas para mostrar las relaciones en sus datos.',
	32.50,
	'Microsoft',
	'visio.png',
	NULL,
	2),

	(NULL, 
	'VM Ware',
	'VM Ware','Gane en flexibilidad y control. Vaya más allá de la virtualización con los servicios multi-cloud para aplicaciones nativas de nube, infraestructura de nube, gestión de nube, seguridad y red, y Anywhere Workspace.',
	32.50,
	'VM Ware',
	'vmware.png',
	NULL,
	2),

	(NULL, 
	'Packet Tracert',
	'Packet Tracert','Packet Tracer de Cisco es un programa de simulación de redes que permite a los estudiantes experimentar con el comportamiento de la red y resolver preguntas del tipo «¿qué pasaría si...?».',
	32.50,
	'Cisco',
	'pt.png',
	NULL,
	2),

	(NULL, 
	'Auto Cat',
	'Auto Cat',
	'AutoCAD es un software de diseño asistido por computadora utilizado para dibujo 2D y modelado 3D. Actualmente es desarrollado y comercializado por la empresa Autodesk',
	32.50,
	'Autodesk',
	'autocat.png',
	NULL,
	2),

	(NULL,
	'Windows 11 Pro',
	'Windows 11 Pro',
	'Windows 11 es el nombre de la versión más reciente del sistema operativo Windows4​ desarrollado por Microsoft, además de ser el sucesor de la anterior versión del sistema operativo, Windows 10,5​6​ lanzado en 2015.7​Fue lanzado oficialmente el 5 de octubre de 2021, como una actualización gratuita a través de Windows Update de Windows 10 para aquellos equipos que cumplan con ciertas especificaciones técnicas compatibles del nuevo sistema operativo.',
	45,
	'Microsoft',
	'win11pro.png',
	NULL,
	2),

	(NULL,
	'Windows 10 Home',
	'Windows 10 Home',
	'Windows 10 es un sistema operativo desarrollado por Microsoft como parte de la familia de sistemas operativos Windows NT.7​ Fue dado a conocer oficialmente en septiembre de 2014, seguido por una breve presentación de demostración en la conferencia Build 2014. Entró en fase beta de prueba en octubre de 2014 y fue lanzado al público en general el 29 de julio de 2015',
	45,
	'Microsoft',
	'win10home.png',
	NULL,
	2),

	(NULL,
	'Windows 10 Pro',
	'Windows 10 Pro',
	'Windows 10 es un sistema operativo desarrollado por Microsoft como parte de la familia de sistemas operativos Windows NT.7​ Fue dado a conocer oficialmente en septiembre de 2014, seguido por una breve presentación de demostración en la conferencia Build 2014. Entró en fase beta de prueba en octubre de 2014 y fue lanzado al público en general el 29 de julio de 2015',
	45,
	'Microsoft',
	'win10pro.png',
	NULL,
	2),

	(NULL,
	'Windows 11 Home',
	'Windows 11 Home',
	'Windows 11 es el nombre de la versión más reciente del sistema operativo Windows4​ desarrollado por Microsoft, además de ser el sucesor de la anterior versión del sistema operativo, Windows 10,5​6​ lanzado en 2015.7​Fue lanzado oficialmente el 5 de octubre de 2021, como una actualización gratuita a través de Windows Update de Windows 10 para aquellos equipos que cumplan con ciertas especificaciones técnicas compatibles del nuevo sistema operativo.',
	45,
	'Microsoft',
	'win11home.png',
	NULL,
	2),

	(NULL,
	'Red Hat Linux',
	'Red Hat Linux',
	'Red Hat fue una distribución Linux creada por Red Hat, ​ que llegó a ser una de las más populares en los entornos de usuarios domésticos hasta el 22 de septiembre de 2003 cuando los proyectos Fedora y Red Hat se fusionaron',
	45,
	'Red Hat',
	'redhat.png',
	NULL,
	2),

	(NULL,
	'Mac OS 11.7',
	'Mac OS 11.7',
	'macOS (previamente Mac OS X, luego OS X) es una serie de sistemas operativos gráficos desarrollados y comercializados por Apple desde 2001. Es el sistema operativo principal para la familia de computadoras Mac de Apple. Dentro del mercado de computadoras de escritorio, portátiles, hogareñas y mediante el uso de la web, fue por años el segundo sistema operativo de escritorio más utilizado, después de Microsoft Windows, hasta 2021.3​4​',
	45,
	'Apple',
	'macos.png',
	NULL,
	2),

	(NULL,
	'Raspberry Pi 3.0',
	'Raspberry Pi 3.0',
	'La Raspberry Pi es una serie de ordenadores monoplaca u ordenadores de placa simple (SBC por las siglas del anglicismo Single Board Computer) de bajo costo desarrollado en el Reino Unido por la Raspberry Pi Foundation, con el objetivo de poner en manos de las personas de todo el mundo el poder de la informática y la creación digital.3​ Si bien el modelo original buscaba la promoción de la enseñanza de informática en las escuelas,4​5​6​ este acabó siendo más popular de lo que se esperaba,7​ hasta incluso vendiéndose fuera del mercado objetivo para usos como robótica',
	45,
	'Raspberry',
	'raspberry.png',
	NULL,
	2),

	(NULL,
	'Windows 7 pro',
	'Windows 7 pro',
	'Windows 7 (Antiguo nombre clave : Vienna ) es una versión de Microsoft Windows, línea de sistemas operativos producida por Microsoft Corporation. Se lanzó en octubre de 2009. Esta versión estaba diseñada para uso en PC, incluyendo equipos de escritorio en hogares y oficinas, equipos portátiles, tabletas, netbooks y equipos multimedia.2​ El desarrollo de Windows 7 se completó el 22 de julio de 2009, siendo entonces confirmada su fecha de venta oficial para el 22 de octubre de 2009 junto a su equivalente para servidores Windows Server 2008 R2.3​ En febrero de 2018, tenía una cuota de mercado de 41,51 %, y fue superado por Windows 10 que ya tenía un 43,95 % de la cuota de mercado.4​',
	45,
	'Microsoft',
	'win7pro.png',
	NULL,
	2),

	(NULL,
	'Windows XP Home',
	'Windows XP Home',
	'Windows XP (Nombre clave: Whistler) también llamado Windows eXPerience es una versión de Microsoft Windows, basado en Windows 2000 y con importantes mejoras. Fue lanzado al mercado el 25 de octubre de 2001. En agosto de 2012, tenía una cuota de mercado de 46,33%, y fue superado por Windows 7 que ya tenía un 46,60% de la cuota de mercado. En diciembre de 2013, tenía una cuota de mercado de 500 millones de ordenadores. Las letras "XP" provienen de la palabra eXPeriencia (eXPerience en inglés). Su nombre clave inicial fue Whistler.',
	45,
	'Microsoft',
	'winxp.png',
	NULL,
	2),

	(NULL,
	'Minecraft Windows 10',
	'Minecraft Windows 10',
	'Minecraft es un videojuego de construcción de tipo «mundo abierto» o sandbox creado originalmente por el sueco Markus Persson, ​ y posteriormente desarrollado por Mojang Studios',
	14.99,
	'Microsoft',
	'minecraft.png',
	NULL,
	2),

	(NULL,
	'Grand Theft Auto V',
	'Grand Theft Auto V',
	'Grand Theft Auto V es un videojuego de acción-aventura de mundo abierto desarrollado por el estudio Rockstar North y distribuido por Rockstar Games. Fue lanzado el 17 de septiembre de 2013 para las consolas PlayStation 3 y Xbox 360.​',
	14.99,
	'Rockstar',
	'gtav.png',
	NULL,
	2),

	(NULL,
	'Uncharted 4',
	'Uncharted 4',
	'Uncharted 4: El desenlace del ladrón, es un videojuego de acción-aventura en tercera persona, lanzado el 10 de mayo de 2016, distribuido por Sony Computer Entertainment y desarrollado por Naughty Dog exclusivamente para PlayStation 4',
	14.99,
	'Naughty Dog',
	'uncharted.png',
	NULL,
	2),

	(NULL,
	'Cyberpunk 2077',
	'Cyberpunk 2077',
	'Cyberpunk 2077 es un videojuego desarrollado y publicado por CD Projekt, que se lanzó para Microsoft Windows, PlayStation 4 y Xbox One el 10 de diciembre de 2020, y posteriormente en PlayStation 5, Xbox Series X|S y Google Stadia',
	14.99,
	'CD Projekt',
	'cyber.png',
	NULL,
	2),

	(NULL,
	'Haf life 2',
	'Haf life 2',
	'Half-Life 2 es la continuación del videojuego Half-Life, una videoaventura de disparos en primera persona. Anteriormente el videojuego se vendía junto a Counter-Strike: Source la secuela de Counter-Strike con el nuevo motor gráfico y el motor físico implantados y los niveles totalmente rediseñados.',
	14.99,
	'Valve Corp.',
	'halflife.png',
	NULL,
	2),

	(NULL,
	'Counter Strike Global Offensive',
	'Counter Strike Global Offensive',
	'Counter-Strike: Global Offensive es un videojuego de disparos en primera persona desarrollado por Valve Corporation y Hidden Path Entertainment. Es el cuarto juego de la saga Counter-Strike. Fue lanzado al mercado en agosto de 2012 para las plataformas de Microsoft Windows, macOS y Xbox 360 y PlayStation 3.',
	14.99,
	'Valve Corp.',
	'csgo.png',
	NULL,
	2),

	(NULL,
	'Metal Gear Solid V',
	'Metal Gear Solid V','Metal Gear Solid es un videojuego de acción-aventura y sigilo de 1998 desarrollado por Konami Computer Entertainment Japan y publicado por Konami para la consola PlayStation.​​ Fue lanzado el 3 de septiembre de 1998 en Japón, ​ el 21 de octubre de 1998 en Norteamérica y el 24 de junio de 1999 en Europa.​​ ',
	14.99,
	'Konami',
	'metalgear.png',
	NULL,
	2),

	(NULL,
	'Call of duty WWII',
	'Call of duty WWII',
	'Call of Duty: WWII es un videojuego de disparos en primera persona desarrollado por Sledgehammer Games, distribuido por Activision, perteneciente a la franquicia Call of Duty y es la decimocuarta entrega de la saga',
	14.99,
	'Activision',
	'ww2.png',
	NULL,
	2),

	(NULL,
	'El Señor de los anillos: Las comunidad del anillo E-book',
	'El Señor de los anillos',
	'«Este libro es como un relámpago en un cielo claro. Decir que la novela heroica, espléndida, elocuente y desinhibida, ha retornado de pronto en una época de un antirromanticismo casi patológico, sería inadecuado. Para quienes vivimos en esa extraña época, el retorno —y el alivio que nos trae— es sin duda lo más importante. Pero para la historia misma de la novela —una historia que se remonta a la Odisea y a antes de la Odisea— no es un retorno, sino un paso adelante o una revolución: la conquista de un territorio nuevo.» —C.S. Lewis, Time & Tide, 1954',
	20,
	'J. R. R. Tolkien',
	'el_señor_anillos.png',
	NULL,
	1),

	(NULL,
	'La Odisea E-book',
	'La Odisea',
	'"La Odisea", del poeta griego Homero, es uno de los poemas épicos más importantes de Occidente. La historia narra el viaje de regreso del héroe Odiseo a su patria, la isla de Ítaca, tras su participación en la guerra de Troya. Su travesía estará llena de peligros y aventuras. "La Odisea" es una metáfora del viaje que es la vida para todos nosotros; de ahí que sea un clásico universal.',
	20,
	'Homero',
	'odisea.png',
	NULL,
	1),

	(NULL,
	'El Quijote E-book',
	'El Quijote ',
	'El Quijote, la novela acaso más original e influyente de la literatura, es también una de las menos leídas por los lectores españoles e hispanohablantes, a menudo buenos y cultivados lectores, abrumados o desalentados por la dificultad de un castellano, el del siglo XVII, más alejado ya del nuestro de lo que se cree. Sólo pensando en ellos y en hacer que el Quijote vuelva a ser esa novela "clara"  en la que no haya "nada que resulte difícil", para que, como decía el bachiller Sansón Carrasco, los niños la manoseen, los mozos la lean, los hombres la entiendan y los viejos la celebren, Trapiello se ha decidido a adaptarla íntegra y fielmente, sin alejarse nunca del maravilloso lenguaje cervantino.',
	20,
	'Miguel de Cervantes',
	'elquijote.png',
	NULL,
	1),

	(NULL,
	'El principito E-book',
	'El principito',
	'La novela fue publicada en abril de 1943, tanto en inglés como en francés, por la editorial estadounidense Reynal and Hitchcock, mientras que la editorial francesa Éditions Gallimard no pudo imprimir la obra hasta 1946, tras la liberación de Francia. Incluido entre los mejores libros del siglo XX en Francia, El principito se ha convertido en el libro escrito en francés más leído y más traducido.',
	20,
	'Antoine de Saint-Exupéry',
	'elprincipito.png',
	NULL,
	1),

	(NULL,
	'Codigo da Vinci E-book',
	'Codigo da Vinci',
	'Robert Langdon recibe una llamada en mitad de la noche: el conservador del museo del Louvre ha sido asesinado en extrañas circunstancias y junto a su cadáver ha aparecido un desconcertante mensaje cifrado. Al profundizar en la investigación, Langdon, experto en simbología, descubre que las pistas conducen a las obras de Leonardo Da Vinci… y que están a la vista de todos, ocultas por el ingenio del pintor.',
	20,
	'Dan Brown',
	'codigodavinci.png',
	NULL,
	1),

	(NULL,
	'20.000 Leguas de viaje submarino E-book',
	'20.000 Leguas de viaje submarino',
	'En la segunda mitad del siglo XIX, la desaparición de numerosos barcos sin una explicación clara hace que navegar los mares ya no sea seguro. Los datos señalan a un monstruo marino, mas grande que una ballena, dotado de una gran velocidad, potencia y que se torna, a veces, fosforescente. Una expedición que incluye al profesor Arronax, un naturalista, saldrá a la mar a intentar develar el misterio. Pero pronto serán atacados por la bestia y los sobrevivientes serán testigos de algo que no creerían si no lo vieran con sus propios ojos.',
	20,
	'Julio Verne',
	'20000leguas.png',
	NULL,
	1),

	(NULL,
	'El mundo de sofía E-book',
	'El mundo de sofía',
	"Alberto Knox és un misteriós i extraordinari professor de filosofia que explica a Sofia Amundsen, una nena de quinze anys, la vida i l'obra dels grans pensadors de la història. Des dels presocràtics fins a Sartre, passant per Plató, Aristòtil, Jesús, sant Agustí, Galileu, Descartes, Hume, la Il·lustració, Kant, el Romanticisme, Hegel, Marx, Darwin o Freud, tots participaran del viatge que emprendrà Sofia pel món de les idees. Però El món de Sofia no és només aquest viatge fascinant, és també una novel·la excepcional i originalíssima, amb un desenllaç imprevisible, que s'ha convertit en un clàssic per a tots els públics.",
	20,
	'Jostein Gaarder',
	'mundosofia.png',
	NULL,
	1),

	(NULL,
	'1984 E-book',
	'1984',
	'In 1984, London is a grim city in the totalitarian state of Oceania where Big Brother is always watching you and the Thought Police can practically read your mind. Winston Smith is a man in grave danger for the simple reason that his memory still functions. Drawn into a forbidden love affair, Winston finds the courage to join a secret revolutionary organization called The Brotherhood, dedicated to the destruction of the Party. Together with his beloved Julia, he hazards his life in a deadly match against the powers that be.',
	20,
	'George Orwell',
	'1984.png',
	NULL,
	1),

	(NULL,
	'10 negritos E-book',
	'10 negritos',
	'The 10 strangers include a reckless playboy, a troubled Harley Street doctor, a formidable judge, an uncouth detective, an unscrupulous mercenary, a God-fearing spinster, two restless servants, a highly decorated general and an anxious secretary. One by one they are picked off. Who will survive? And who is the killer? Copies of an ominous nursery rhyme hang in each room, the murders mimicking the awful fates of its ‘Ten Little Soldier Boys’.',
	20,
	'Agatha Christie',
	'10negritos.png',
	NULL,
	1),

	(NULL,
	'Un mundo feliz E-book',
	'Un mundo feliz ',
	'Los peores vaticinios del capitalismo se han cumplido: triunfan los dioses del consumo y la comodidad, y el orbe se divide en diez zonas en apariencia seguras y estables. Los humanos ya no procrean, el sexo se ha convertido solo en una diversión y las letras del alfabeto griego se han pervertido para clasificar a los seres humanos por castas. Todos aceptan su lugar en la nueva jerarquía social, perfectamente ordenada. Los valores humanos esenciales no tienen cabida en este mundo y los habitantes se crean in vitro con una técnica concebida a imagen y semejanza de una cadena de montaje. El soma, la droga por excelencia en este mundo distópico que propone Huxley, ayuda a los habitantes a escapar de la rutina.',
	20,
	'Aldous Huxley',
	'mundofeliz.png',
	NULL,
	1),

	(NULL,
	'League of Legends',
	'League of Legends',
	'League of Legends, es un videojuego multijugador de arena de batalla en línea desarrollado y publicado por Riot Games. Inspirándose en Defense of the Ancients, un mapa personalizado para Warcraft III, los fundadores de Riot buscaron desarrollar un juego independiente del mismo género.',
	14.99,
	'Riot Games',
	'lol.png',
	NULL,
	2),

	(NULL,
	'Dark Souls III',
	'Dark Souls III',
	'Dark Souls III es un videojuego de rol de acción desarrollado por FromSoftware y publicado por Bandai Namco Entertainment para PlayStation 4, Xbox One y Microsoft Windows. Es la tercera entrega en la saga Souls, ​ Dark Souls III fue lanzado en Japón en marzo de 2016, y de manera mundial en abril del mismo año',
	14.99,
	'FromSoftware',
	'darksouls.png',
	NULL,
	2),

	(NULL,
	'Nike Air Force 1 (Gs) Zapatillas de baloncesto unisex',
	'Airforce 1',
	'Fabricadas con materiales exclusivos para un aspecto elegante y máxima comodidad, las Nike Air Force 1 están diseñadas con un estilo vintage y una excelente amortiguación. El zapato está fabricado con piel para mayor comodidad y durabilidad, con una entresuela acolchada para tracción y durabilidad. La tradicional unidad Nike Air encapsulada sigue estando presente para proporcionar una amortiguación ligera y una protección contra los impactos.',
	120.90,
	'Nike',
	'airforce1.png',
	NULL,
	4),

	(NULL,
	'Nike Air NSW - Chándal Completo para Hombre',
	'Chandal Nike',
	'Nike Sportswear Track Suit Kick Back en Nike Air Style Comfort se bloquea el color con el Nike Sportswear Track Suit Hecho con tela de forro polar suave, cuenta con un diseño de bloqueo de color, una acogedora capucha y los pops de logo aman por todo. La tela de forro polar cepillado es suave y cálida. Los paneles de colores añaden estilo de contraste. Logotipos Nike Air impresos en el pecho y las piernas. Bolsillo de canguro dividido para un almacenamiento cómodo.',
	120.90,
	'Nike',
	'chandalnike.png',
	NULL,
	4),

	(NULL,
	"Levi's 501 Original Vaqueros para Hombre",'Vaquero Levis',
	'Lo que empezó como ropa de trabajo para los jornaleros del oeste americano muy pronto acabó siendo adoptado como símbolo universal de modernidad. Y es que unos Levi’s son mucho más. Son una forma de expresión. Van adquiriendo sutiles marcas de uso que te representan, se adaptan a tus formas e incorporan recuerdos de aventuras vividas.',
	120.90,
	'Levi´s',
	'pantalon_levis.png',
	NULL,
	4),

	(NULL,
	'Guess Delvina Dress Vestido para Mujer',
	'Vestido Guess',
	'El vestido, palabra proveniente del latín vestitus, puede servir para designar un traje de mujer.1​ Si nos atenemos a una definición más estricta, un vestido se compone concretamente de una falda y cuerpo en una misma pieza y tela. Hasta los años 60 del siglo XX será considerado como un elemento básico de la moda femenina, siendo desde entonces un elemento menos frecuente en su uso, relegado en ocasiones a celebraciones especiales.2​',
	120.90,
	'Guess',
	'vestido_guess.png',
	NULL,
	4),

	(NULL,
	'Guess Bolso mujer HWVG7455230 COGNAC',
	'Bolso Guess',
	'GUESS Bolso de mujer de piel sintética reversible, doble asa y cierre central con gancho, interiores desenfundados con la presencia de un bolso cerrado con cremallera. Medidas Longitud 40 cm Altura 30 cm Profundidad 15 cm',
	120.90,
	'Guess',
	'bolso_guess.png',
	NULL,
	4),

	(NULL,
	'Reloj Gucci para Hombre YA126442',
	'Reloj Gucci',
	'Cuarzo Unisex Reloj De Pulsera ya126442 con carcasa de acero inoxidable, con diámetro de 38 mm, esfera de plata y banda de acero inoxidable de plata.<br/>Género: Unisex<br/>Estilo: Vestido<br/>Tipo de Movimiento: Cuarzo<br/>Alimentado por: cuarzo<br/>Movimiento Fabricante: Swiss<br/>Tipo de calendario: Fecha<br/>Resistencia al Agua: 50 m (5 ATM<br/>Tipo de Pantalla: Analógica<br/>Material de la caja: Acero Inoxidable<br/>Caso color: plata<br/>Caso Forma: Redondo<br/>Diámetro de la Carcasa: 38 mm<br/>Espesor del estuche: 8 mm<br/>Tipo de cristal: zafiro sintético<br/>Forma del dial: Redondo<br/>Dial de Color: Plata<br/>Tipo de índice: Geometrics<br/>Índice de color: Dorado<br/>Material de la correa: Acero Inoxidable<br/>Color de la correa: Plata<br/>Tipo de cierre: Cierre de botón',
	120.90,
	'Gucci',
	'reloj_gucci.png',
	NULL,
	4),

	(NULL,
	'Champion Legacy-Classic Logo S/S Camiseta para Mujer',
	'Camisera Champion',
	'efresca tu gama de básicos con nuestras camisetas tradicionales Champion. Esta camiseta de cuello redondo está detallada con nuestro gran logotipo clásico impreso en el pecho y el tradicional logotipo C impreso en la manga izquierda. Disfruta combinándolo con un par de nuestros pantalones de chándal o leggings esenciales.',
	120.90,
	'Champion',
	'camiseta_champion.png',
	NULL,
	4),

	(NULL,
	'Guitarra clásica española para principiantes de tamaño estándar 4/4 con cuerdas de nylon con 6 meses de clases y funda de transporte – Natural',
	'Guitarra Española',
	'GUITARRA ÓPTIMA PARA PRINCIPIANTES – Esta guitarra clásica de 3rd avenue es el instrumento óptimo para aprender, incluye funda de transporte y almacenamiento ligera sin coste adicional y es un regalo de cumpleaños o navidad adecuado para familiares y amigos tanto adultos como adolescentes
	GUITARRA PARA PRINCIPIANTES - guitarra clásica española de tamaño estándar y seis cuerdas para diestros con cuerdas de nylon de baja tensión fáciles de pulsar y tocar que te proporcionan más comodidad mientras aprendes, además, posee un diapasón liso para que puedas cambiar de acorde si esfuerzo y una altura de cuerdas baja que hará que tocarla te resulte increíblemente fácil y agradable
	GUITARRA DE FABRICACIÓN ARTESANAL - guitarra acústica clásica hecha a mano con diseño tradicional, tapa anterior de álamo de color natural y braceado en x festoneado para una durabilidad y resonancia continuadas, su tapa posterior y costados de color burdeos son de tilo para proporcionar un tono cálido y redondo, además, su diapasón de arce tintado con bindings de protección y su clavijero de engranajes en líneas de tres te proporcionarán un afinado invariablemente preciso
	TAMAÑO Y ESPECIFICACIONES - gracias a su tamaño de 4/4, esta guitarra para principiantes es óptima para adultos que quieran iniciarse en este instrumento o niños que quieran progresar a un modelo de tamaño estándar, también disponible en los tamaños 3/4, 1/2 y 1/4, que son los idóneos para niños, todas las variantes son óptimas para clases, ensayos, prácticas y actuaciones, longitud total: 39”/99,5 cm, longitud de escala: 25,5”/65 cm, ancho de la caja: 15”/38 cm, número de trastes: 19 trastes, material de las cuerdas: nylon',
	260,
	'Guitarra',
	'guitarra_esp.png',
	NULL,
	5),

	(NULL,
	'Tuyama TAS-131 Saxofón Alto en Mi Bemol',
	'Saxofón',
	'Due to its easy response and excellent intonation, the TAS-131 has been one of our bestsellers for years. Yellow brass body, lacquered. High F# key. High quality Soundman D5 mouthpiece and robust case with backpack straps included',
	260,
	'Saxofón',
	'saxo.png',
	NULL,
	5),

	(NULL,
	'YAMAHA PSR-E273 - Teclado digital, Función de aprendizaje, 61 teclas, 143 estilos automáticos, negro',
	'Piano',
	'Los grandes y pequeños maestros tienen algo en común: ¡todos quieren divertirse mientras practican! El tecladoPSR-E273 es un instrumento ligero para principiantes y el acompañante adecuado para dar los primeros pasos musicales. Dotado de una gran variedad de sonidosinstrumentales, una práctica función de aprendizaje y estilos rítmicos de acompañamiento, elPSR-E273 ofrece una iniciación excitante para tocar el teclado. El modo Duo permite que dos personas practiquen al mismo tiempo.',
	260,
	'Yamaha',
	'piano.png',
	NULL,
	5),

	(NULL,
	'Vangoa Pack Bajo Electrico 4 Cuerdas Bajo Eléctrico Tamaño Completo, E Bajo Sunburst para Principiantes',
	'Bajo',
	'🎸【Diseño de moda y garantía de calidad】El bajo eléctrico tiene un cuerpo de álamo sólido que puede soportar años de uso y desgaste. Diapasón de Blackwood, mástil de arce, acabado premium en la parte posterior del mástil, que proporciona una sensación de traste suave para comodidad y rendimiento, lo que le permite tocar libremente
	🎸【Tono encantador】Vangoa Beginner Electric Bass adopta la pastilla P-bass (Precision-Bass), lo que facilita tocar el tono, proporciona un tono profundo y cálido y un rango medio fuerte, y siempre es la primera opción de los bajistas',
	260,
	'Yamaha',
	'bajo.png',
	NULL,
	5),

	(NULL,
	'Yinfente Intermediate B-Flat Clarinete Madera Palisandro Cuerpo Placa Plata Llave Bb 17 Llaves + Cañas + Almohadillas (Bb Key)',
	'Clarinete',
	'Clarinete de la marca Yinfente comprueba cada detalle cuidadosamente. Fabricado por más de 30 años de experiencia profesional fabricante. Asegúrate de todo en perfectas condiciones.',
	260,
	'Yainfente',
	'clarinete.png',
	NULL,
	5),

	(NULL,
	'Sans Luthier CH04 - Chalumeau',
	'Flauta',
	'El chalumeau es un instrumento de viento antiguo, anterior al actual clarinete, de caña simple que está compuesto por un cuerpo de madera con la misma digitación que la flauta dulce (digitación alemana) y con boquilla de clarinete. Es de finales del barroco y principios de la época clásica. Está muy bien valorado porque representa una alternativa a la flauta, es fácil de tocar y tiene un sonido suave y cálido.',
	260,
	'Sans',
	'flauta.png',
	NULL,
	5),

	(NULL,
	'Foto del director de pastoral de FP - Salesianos atocha',
	'Lauro',
	'Foto enmarcada en plata de ley. 18 x 32 cm. La foto es de nuestro querido director de pastoral, para que la coloques en el salón de tu casa o donde quieras.',
	0.99,
	'Salesianos',
	'lauro.png',
	NULL,
	6),

	(NULL,
	'Vale por un aprobado en examen de Linux -SSOO',
	'SSOO',
	'Un examen es una prueba de conocimiento aptitudes, habilidades o de las capacidades físicas. En cualquier nivel educativo existe la necesidad de evaluar para conocer el aprovechamiento del estudio, lo que se conoce como “calificación”. La evaluación ofrece una oportunidad real de demostrar lo que los sujetos saben y cómo lo saben, pues el profesor podrá detectar los conocimientos adquiridos. (este vale aprueba automáticamente el examen en cuestión)',
	0.99,
	'Salesianos',
	'vale_linux.png',
	NULL,
	6),

	(NULL,
	'Vale por un aprobado en examen de PHP - IAW',
	'IAW',
	'Un examen es una prueba de conocimiento aptitudes, habilidades o de las capacidades físicas. En cualquier nivel educativo existe la necesidad de evaluar para conocer el aprovechamiento del estudio, lo que se conoce como “calificación”. La evaluación ofrece una oportunidad real de demostrar lo que los sujetos saben y cómo lo saben, pues el profesor podrá detectar los conocimientos adquiridos. (este vale aprueba automáticamente el examen en cuestión)',
	0.99,
	'Salesianos',
	'vale_php.png',
	NULL,
	6),

	(NULL,
	'Vale por un aprobado en examen de Redes - Samu',
	'Redes',
	'Un examen es una prueba de conocimiento aptitudes, habilidades o de las capacidades físicas. En cualquier nivel educativo existe la necesidad de evaluar para conocer el aprovechamiento del estudio, lo que se conoce como “calificación”. La evaluación ofrece una oportunidad real de demostrar lo que los sujetos saben y cómo lo saben, pues el profesor podrá detectar los conocimientos adquiridos. (este vale aprueba automáticamente el examen en cuestión)',
	0.99,
	'Salesianos',
	'vale_redes.png',
	NULL,
	6),

	(NULL,
	'Vale por el aprobado de este proyecto',
	'Proyecto',
	'Un proyecto es una planificación que consiste en un conjunto de objetivos que se encuentran interrelacionados y coordinados.1​ De conformidad con el Project Management Institute (PMI), "un proyecto es un esfuerzo temporal que se lleva a cabo para crear un producto, servicio o resultado único".2​ De estos conceptos, se evidencia que la razón de un proyecto es alcanzar resultados o metas específicas dentro de los límites que imponen un presupuesto, calidades establecidas previamente, y un lapso de tiempo previamente definido. (Este vale aprueba el proyecto en cuestión automáticamente)',
	0.99,
	'Salesianos',
	'vale_proyecto.png',
	NULL,
	6),

	(NULL,
	'Vale Laboral. Envió a FCT en Telefónica España',
	'FCT',
	'Al canjear este vale, se manda al "chaval" a hacer las FCT en Telefónica de cabeza. Apto para espabilados.',
	0.99,
	'Salesianos',
	'vale_fct.png',
	NULL,
	6);

INSERT INTO valoracion (id_valoracion, titulo_valoracion, texto_valoracion, fecha, rate, imagen, id_producto, id_usuario) VALUES
	(NULL, "10 de 10", "Me encanta, lo recomiendo", "2022/02/14", 5, "valoracion1.jpg", 1, 2),
	(NULL, "Buen regalo", "Compre uno para mi sobrino y es genial", "2019/02/14", 4, "valoracion2.jpg", 12, 2),
	(NULL, "Encatada", "Lo compre para mi hija y esta encantada", "2021/01/02", 4, "valoracion3.jpg", 16, 1),
	(NULL, "Peliculoncio", "De las mejores pelis de la historia", "2022/02/14", 5, "valoracion5.jpg", 1, 2),
	(NULL, "Menuda patraña", "Nunca la remonderé a nadie, es mejor verla pirata que comprar este bodrio", "2021/01/02", 0, NULL, 1, 1),
	(NULL, "No lo compres", "Es una mierda, lo he devuelto", "2020/11/30", 1, NULL, 10, 2);

INSERT INTO publicidad ( id_publicidad, logo_marca, titulo, precio, img ) VALUES
	(1, "Apple", "Descubre lo mejor de Iphone", 780, "apple.jpg");


INSERT INTO publicidad ( id_publicidad, logo_marca, titulo, precio, img ) VALUES
	(1, "Apple", "Descubre lo mejor de Iphone", 780, "apple.jpg");